export const listSlides = [
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/utils-387101.appspot.com/o/sanpham%2F1.png?alt=media&token=2e3c6fbf-860b-4cc8-8bc3-ecea876fd9db&_gl=1*1rdj3rv*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTk5MTI3Ny4zMy4xLjE2ODU5OTIwOTguMC4wLjA.",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/utils-387101.appspot.com/o/sanpham%2F10.png?alt=media&token=dc362b9b-6ec4-44a6-b00e-e5c64458a3dd&_gl=1*1i9q59p*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTk5MTI3Ny4zMy4xLjE2ODU5OTIxMDAuMC4wLjA.",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/utils-387101.appspot.com/o/sanpham%2F11.png?alt=media&token=eedd245e-f5bc-4d89-8e4b-50c6cfaeea3e&_gl=1*1ls6bbt*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTk5MTI3Ny4zMy4xLjE2ODU5OTIxMDIuMC4wLjA.",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/utils-387101.appspot.com/o/sanpham%2F13.png?alt=media&token=c08514db-7439-4aa9-9203-a8b599828341&_gl=1*1oe8fj7*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTk5MTI3Ny4zMy4xLjE2ODU5OTIxMDMuMC4wLjA.",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/utils-387101.appspot.com/o/sanpham%2F15.png?alt=media&token=c07e770d-e857-49ed-99b4-b3564d9bc65c&_gl=1*1wsi6up*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTk5MTI3Ny4zMy4xLjE2ODU5OTIxMDYuMC4wLjA.",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/Image.png",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro1.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro2.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro10.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro11.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro12.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro13.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro14.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro15.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro16.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro3.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro4.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro5.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro6.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro7.jpg",
  },
];
