export const listSlides = [
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/isuzusuzukisoctrang.appspot.com/o/slider%2F1.png?alt=media&token=c49b8914-6442-4688-9cdd-f35396847cb9&_gl=1*1n53b2*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTQxMTc0NC44LjAuMTY4NTQxMTc0NC4wLjAuMA..",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/isuzusuzukisoctrang.appspot.com/o/slider%2F2.png?alt=media&token=849133b6-97f0-418f-a373-70c6998ff75e&_gl=1*1rqomuw*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTQxMTc0NC44LjEuMTY4NTQxMTc0Ny4wLjAuMA..",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/isuzusuzukisoctrang.appspot.com/o/slider%2F3.png?alt=media&token=aadca294-24ba-48fd-bdb1-3ad309afe4c2&_gl=1*79g5fo*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTQxMTc0NC44LjEuMTY4NTQxMTc0OS4wLjAuMA..",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/isuzusuzukisoctrang.appspot.com/o/slider%2F4.png?alt=media&token=ad863c8d-08a3-4f4a-8ced-5156be084e74&_gl=1*1qi5h52*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTQxMTc0NC44LjEuMTY4NTQxMTc1Mi4wLjAuMA..",
  },
  {
    image:
      "https://firebasestorage.googleapis.com/v0/b/isuzusuzukisoctrang.appspot.com/o/slider%2F5.png?alt=media&token=71dcab6d-665b-4281-b8dc-6763a68acbbe&_gl=1*pk6gku*_ga*MTA1MjQ5NTQ0OS4xNjg0NDAxMjc5*_ga_CW55HF8NVT*MTY4NTQxMTc0NC44LjEuMTY4NTQxMTc1NS4wLjAuMA..",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/Image.png",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro1.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro2.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro10.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro11.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro12.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro13.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro14.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro15.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro16.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro3.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro4.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro5.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro6.jpg",
  },
  {
    image:
      "https://ads-company-storage.s3.ap-southeast-2.amazonaws.com/isuzusuzukisoctrang/intro7.jpg",
  },
];
